<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Insights Report - {{ $restaurant->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            margin: 30px;
            color: #333;
            line-height: 1.6;
        }
        h1, h2 {
            color: #1e40af;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 8px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background: #f1f5f9;
            font-weight: bold;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #3b82f6;
        }
        .summary {
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .good { color: #22c55e; }
        .warning { color: #eab308; }
        .danger { color: #ef4444; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Insights Report</h1>
        <p><strong>{{ $restaurant->name }}</strong> | Generated on: {{ now()->format('d M Y, H:i') }}</p>
    </div>

    @if(isset($data['menu']))
    <h2>📋 Menu Items</h2>
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Price</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['menu'] as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>₹{{ number_format($item->price, 2) }}</td>
                <td>{{ $item->is_active ? 'Active' : 'Inactive' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(isset($data['orders']))
    <h2>📦 Recent Orders</h2>
    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Customer</th>
                <th>Total</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['orders'] as $order)
            <tr>
                <td>#{{ $order->id }}</td>
                <td>{{ $order->customer_name ?: 'Walk-in' }}</td>
                <td>₹{{ number_format($order->total, 2) }}</td>
                <td>{{ ucfirst($order->status) }}</td>
                <td>{{ $order->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(isset($data['revenue']))
    <h2>💰 Revenue Summary</h2>
    <table>
        <thead>
            <tr>
                <th>Period</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>Today</strong></td>
                <td>₹{{ number_format($data['revenue']['today'], 2) }}</td>
            </tr>
            <tr>
                <td><strong>This Month</strong></td>
                <td>₹{{ number_format($data['revenue']['this_month'], 2) }}</td>
            </tr>
            <tr>
                <td><strong>Total</strong></td>
                <td>₹{{ number_format($data['revenue']['total'], 2) }}</td>
            </tr>
        </tbody>
    </table>
    @endif

    @if(isset($data['inventory']))
    <h2>📦 Inventory Status</h2>
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Total Stock</th>
                <th>Remaining</th>
                <th>Minimum</th>
                <th>Status</th>
                <th>Active</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['inventory'] as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ $item->total_stock }}</td>
                <td>{{ $item->remaining_stock }}</td>
                <td>{{ $item->minimum_stock }}</td>
                <td>
                    @if($item->remaining_stock <= 0)
                        <span style="color:#ef4444">Out of Stock</span>
                    @elseif($item->remaining_stock <= $item->minimum_stock)
                        <span style="color:#eab308">Low Stock</span>
                    @else
                        <span style="color:#22c55e">In Stock</span>
                    @endif
                </td>
                <td>{{ $item->is_active ? 'Yes' : 'No' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div style="margin-top: 40px; text-align: center; color: #666; font-size: 0.8rem;">
        Generated by Insights Dashboard • {{ now()->format('d M Y H:i:s') }}
    </div>

</body>
</html>
